#!/bin/bash

# Generate Daily Summary Report for MCP Hub
# Combines performance metrics, anomaly detection, and alert status

set -e

SUMMARY_DATE=$(date +%Y-%m-%d)
SUMMARY_TIME=$(date +%H:%M:%S)
STATE_DIR="${XDG_STATE_HOME:-$HOME/.local/state}/mcp-hub/monitoring"
SUMMARY_FILE="$STATE_DIR/daily-summary-${SUMMARY_DATE}.md"

mkdir -p "$STATE_DIR"

echo "📊 Generating Daily Summary Report..."
echo "Date: $SUMMARY_DATE $SUMMARY_TIME"
echo "Output: $SUMMARY_FILE"

# Generate report
cat > "$SUMMARY_FILE" << EOF
# MCP Hub Daily Summary - ${SUMMARY_DATE}

**Generated:** ${SUMMARY_DATE} ${SUMMARY_TIME}
**Report Type:** Automated Daily Summary

---

## Quick Status

\`\`\`
$(curl -s http://127.0.0.1:7000/api/health | jq -r '
  "Hub State:       \(.state)",
  "Active Clients:  \(.activeClients)",
  "Total Servers:   \(.servers | length)",
  "Connected:       \([.servers[] | select(.status == "connected")] | length)",
  "Disconnected:    \([.servers[] | select(.status == "disconnected")] | length)",
  "Disabled:        \([.servers[] | select(.status == "disabled")] | length)"
' 2>/dev/null || echo "ERROR: Could not fetch health status")
\`\`\`

---

## Performance Metrics

\`\`\`
$(bash scripts/measure-performance.sh 2>&1 | sed 's/\x1b\[[0-9;]*m//g')
\`\`\`

---

## Alert Status

\`\`\`
$(bash scripts/check-alerts.sh 2>&1 | sed 's/\x1b\[[0-9;]*m//g')
\`\`\`

---

## Anomaly Detection

\`\`\`
$(bash scripts/monitoring/detect-anomalies.sh 2>&1 | sed 's/\x1b\[[0-9;]*m//g')
\`\`\`

---

## Server Status Details

\`\`\`json
$(curl -s http://127.0.0.1:7000/api/health | jq '
  [.servers | group_by(.status) | .[] | {
    status: .[0].status,
    count: length,
    servers: [.[] | .name]
  }]
' 2>/dev/null || echo "[]")
\`\`\`

---

## Resource Usage

\`\`\`
$(ps aux | grep -E "bun.*start" | grep -v grep | awk '{printf "CPU: %.1f%%, Memory: %.1f%% (%d KB)\n", $3, $4, $6}')
\`\`\`

---

## Log Summary

\`\`\`
Recent Errors:
$(tail -100 ~/.local/state/mcp-hub/logs/mcp-hub.log | grep -i error | tail -5 || echo "No recent errors")

Recent Warnings:
$(tail -100 ~/.local/state/mcp-hub/logs/mcp-hub.log | grep -i warn | tail -5 || echo "No recent warnings")
\`\`\`

---

## Actions Required

EOF

# Analyze and add action items
if curl -s http://127.0.0.1:7000/api/health | jq -e '[.servers[] | select(.status == "disconnected")] | length > 0' > /dev/null 2>&1; then
  cat >> "$SUMMARY_FILE" << EOF
- ⚠️ **Investigate disconnected servers**
  \`\`\`
$(curl -s http://127.0.0.1:7000/api/health | jq -r '
  [.servers[] | select(.status == "disconnected") | "  - \(.name): \(.error // "Unknown error")"] | .[]
' 2>/dev/null)
  \`\`\`

EOF
fi

# Check for high error rate in logs
ERROR_COUNT=$(tail -1000 ~/.local/state/mcp-hub/logs/mcp-hub.log 2>/dev/null | grep -c -i error || echo 0)
if [ "$ERROR_COUNT" -gt 10 ]; then
  cat >> "$SUMMARY_FILE" << EOF
- ⚠️ **High error rate detected:** $ERROR_COUNT errors in last 1000 log lines

EOF
fi

# Check for memory growth
MEMORY_KB=$(ps aux | grep -E "bun.*start" | grep -v grep | awk '{print $6}' | head -1)
if [ "$MEMORY_KB" -gt 500000 ]; then  # >500 MB
  cat >> "$SUMMARY_FILE" << EOF
- ⚠️ **Memory usage elevated:** ${MEMORY_KB} KB (>500 MB threshold)

EOF
fi

# Default if no actions
if ! grep -q "⚠️" "$SUMMARY_FILE"; then
  cat >> "$SUMMARY_FILE" << EOF
- ✅ No action required - all metrics healthy

EOF
fi

cat >> "$SUMMARY_FILE" << EOF
---

## Next Review

**Tomorrow:** $(date -d tomorrow +%Y-%m-%d) 00:00:00
**Weekly Review:** $(date -d "next Sunday" +%Y-%m-%d) 02:00:00

---

*Report auto-generated by MCP Hub monitoring system*
EOF

echo "✅ Daily summary generated: $SUMMARY_FILE"
echo ""
echo "📖 View report:"
echo "   cat $SUMMARY_FILE"
echo "   less $SUMMARY_FILE"
echo ""

# Output summary to stdout as well
cat "$SUMMARY_FILE"
