#!/bin/bash

# Setup Monitoring Automation for MCP Hub
# Creates cron jobs for continuous production monitoring

set -e

PROJECT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
STATE_DIR="${XDG_STATE_HOME:-$HOME/.local/state}/mcp-hub/monitoring"
CRON_CONFIG="/tmp/mcp-hub-cron-setup.txt"

echo "🔧 MCP Hub Monitoring Automation Setup"
echo "========================================"
echo ""
echo "Project Directory: $PROJECT_DIR"
echo "Monitoring State:  $STATE_DIR"
echo ""

# Create monitoring directories
mkdir -p "$STATE_DIR"
mkdir -p "$PROJECT_DIR/baselines"

# Generate cron configuration
cat > "$CRON_CONFIG" << 'EOF'
# MCP Hub Production Monitoring
# Auto-generated by scripts/setup-monitoring-automation.sh

# Hourly anomaly detection (9 AM - 6 PM weekdays)
0 9-18 * * 1-5 cd PROJECT_DIR && bash scripts/monitoring/detect-anomalies.sh >> STATE_DIR/continuous.log 2>&1

# Daily performance baseline (11:59 PM every day)
59 23 * * * cd PROJECT_DIR && bash scripts/measure-performance.sh >> STATE_DIR/daily-summary.log 2>&1

# Daily summary report (midnight)
0 0 * * * cd PROJECT_DIR && bash scripts/monitoring/generate-daily-summary.sh >> STATE_DIR/daily-summary.log 2>&1

# Weekly comprehensive validation (Sunday 2 AM)
0 2 * * 0 cd PROJECT_DIR && bash scripts/monitoring/phase1-validation.sh >> STATE_DIR/weekly-analysis.log 2>&1

# Weekly log rotation (Sunday 3 AM)
0 3 * * 0 find STATE_DIR -name "*.log" -type f -mtime +30 -delete 2>&1
EOF

# Replace placeholders
sed -i "s|PROJECT_DIR|$PROJECT_DIR|g" "$CRON_CONFIG"
sed -i "s|STATE_DIR|$STATE_DIR|g" "$CRON_CONFIG"

echo "📋 Cron Configuration Generated:"
echo "--------------------------------"
cat "$CRON_CONFIG"
echo ""
echo "--------------------------------"
echo ""

# Offer to install cron jobs
echo "❓ Install these cron jobs?"
echo "   This will add monitoring tasks to your user crontab."
echo ""
echo "   [y] Install cron jobs automatically"
echo "   [n] Show manual installation instructions"
echo "   [s] Skip (you can run this script later)"
echo ""

read -p "Choice [y/n/s]: " choice

case "$choice" in
  y|Y)
    echo ""
    echo "📝 Installing cron jobs..."

    # Backup existing crontab
    if crontab -l > /dev/null 2>&1; then
      crontab -l > "$STATE_DIR/crontab-backup-$(date +%Y%m%d-%H%M%S).txt"
      echo "✅ Existing crontab backed up to $STATE_DIR/"
    fi

    # Add MCP Hub monitoring jobs
    (crontab -l 2>/dev/null || echo ""; cat "$CRON_CONFIG") | crontab -
    echo "✅ Cron jobs installed successfully!"
    echo ""
    echo "🔍 Verify installation:"
    echo "   crontab -l | grep 'MCP Hub'"
    ;;

  n|N)
    echo ""
    echo "📖 Manual Installation Instructions:"
    echo "======================================"
    echo ""
    echo "1. Open your crontab:"
    echo "   crontab -e"
    echo ""
    echo "2. Add these lines:"
    echo "   (Copy from: $CRON_CONFIG)"
    echo ""
    cat "$CRON_CONFIG"
    echo ""
    echo "3. Save and exit"
    echo ""
    echo "4. Verify:"
    echo "   crontab -l"
    ;;

  s|S)
    echo ""
    echo "⏭️  Skipped. Configuration saved to:"
    echo "   $CRON_CONFIG"
    echo ""
    echo "You can install later by running:"
    echo "   bash $PROJECT_DIR/scripts/setup-monitoring-automation.sh"
    ;;

  *)
    echo ""
    echo "❌ Invalid choice. Exiting without changes."
    exit 1
    ;;
esac

echo ""
echo "📊 Next Steps:"
echo "=============="
echo ""
echo "1. Test Monitoring Scripts:"
echo "   bash scripts/monitor-production.sh       # Real-time dashboard"
echo "   bash scripts/measure-performance.sh      # Performance baseline"
echo "   bash scripts/check-alerts.sh             # Alert validation"
echo "   bash scripts/monitoring/detect-anomalies.sh  # Anomaly detection"
echo ""
echo "2. Review Logs:"
echo "   tail -f $STATE_DIR/continuous.log"
echo "   tail -f $STATE_DIR/daily-summary.log"
echo ""
echo "3. Check Baselines:"
echo "   ls -lh $PROJECT_DIR/baselines/"
echo ""
echo "✅ Monitoring automation setup complete!"
